Repository gumberoo/gumberoo, pull requests merged in 2020-09, with the labels that each got.

#46 Feature/studentdashboard
  package-lock.json
  package.json
  src/App/App.js
  src/LessonPreview/LessonPreview.js
  src/StudentDashboard/MoodForm.js
  src/StudentDashboard/MoodForm.scss
  src/StudentDashboard/MoodForm.test.js
  src/StudentDashboard/QuestionArea.js
  src/StudentDashboard/QuestionArea.scss
  src/StudentDashboard/QuestionArea.test.js
  src/StudentDashboard/StudentDashboard.js
  src/StudentDashboard/StudentDashboard.scss
  src/StudentDashboard/StudentDashboard.test.js
  src/StudentDashboard/StudentForm.js
  src/StudentDashboard/StudentForm.scss
  src/StudentDashboard/StudentForm.test.js
  src/TeacherHeader/TeacherHeader.test.js
  src/TeacherLogin/TeacherLogin.test.js
  src/actions/index.js
  src/actions/index.test.js
  src/index.scss
  src/mockData/mockData.js
  src/reducers/addLesson.js
  src/reducers/addLesson.test.js
  src/reducers/hasErrored.js
  src/reducers/hasErrored.test.js
  src/reducers/index.js
  src/reducers/isLoading.js
  src/reducers/isLoading.test.js
  src/reducers/setCurrentQuestion.js
  src/reducers/setCurrentQuestion.test.js
  src/reducers/setLesson.js
  src/reducers/setLesson.test.js
  src/reducers/setLessonOver.js
  src/reducers/setLessonOver.test.js
  src/reducers/setScore.js
  src/reducers/setScore.test.js
  src/reducers/setStudentName.js
  src/reducers/setStudentName.test.js
  src/reducers/setStudents.js
  src/reducers/setStudents.test.js
Labels: FE, Phase 2

#54 Updates .yml for heroku deployment
  .travis.yml
Labels: FE, Phase 3

#55 Adds correct api key
  .travis.yml
Labels: FE, Phase 3

#61 Testing/create lesson
  src/App/App.js
  src/CreateLesson/CreateLesson.test.js
  src/QuestionFormCard/AnswerInput/AnswerInput.js
  src/mockData/mockData.js
Labels: FE, Phase 2

#62 Feature/thunk
  src/App/App.js
  src/StudentDashboard/MoodForm.js
  src/StudentDashboard/MoodForm.test.js
  src/StudentDashboard/QuestionArea.js
  src/StudentDashboard/QuestionArea.test.js
  src/StudentDashboard/StudentDashboard.js
  src/StudentDashboard/StudentDashboard.test.js
  src/StudentDashboard/StudentForm.js
  src/StudentDashboard/StudentForm.test.js
  src/actions/index.js
  src/actions/index.test.js
  src/reducers/index.js
  src/reducers/setLessons.js
  src/reducers/setStudent.js
  src/reducers/setStudent.test.js
  src/reducers/setStudentName.js
  src/reducers/setTeacher.js
  src/reducers/setTeacher.test.js
  src/thunks/__tests__/getTeacher.js
  src/thunks/getLesson.js
  src/thunks/getLessons.js
  src/thunks/getStudents.js
  src/thunks/getTeacher.js
Labels: FE

#64 Feature/Teacherdashboard
  src/App/App.js
  src/TeacherDashboard/TeacherDashboard.js
  src/TeacherDashboard/TeacherDashboard.scss
  src/TeacherDashboard/TeacherDashboard.test.js
  src/TeacherHeader/TeacherHeader.js
Labels: FE, Phase 2, enhancement

#71 Feature/animations
  package-lock.json
  package.json
  src/App/App.js
  src/StudentDashboard/MoodForm.js
  src/StudentDashboard/MoodForm.scss
  src/StudentDashboard/QuestionArea.scss
  src/StudentDashboard/StudentDashboard.js
  src/StudentDashboard/StudentDashboard.scss
  src/StudentDashboard/assets/PandaJumpAndRandom.png
  src/TeacherHeader/TeacherHeader.js
  src/_redirects
  src/fontAssets/OpenDyslexic-Regular.otf
  src/fontAssets/opendyslexic-regular-webfont.woff
  src/index.scss
Labels: FE, Phase 4

#73 Styling/studentdash
  src/App/App.js
  src/StudentDashboard/MoodForm.js
  src/StudentDashboard/MoodForm.scss
  src/StudentDashboard/QuestionArea.scss
  src/StudentDashboard/QuestionArea.test.js
  src/StudentDashboard/StudentDashboard.js
  src/StudentDashboard/StudentDashboard.scss
  src/StudentDashboard/StudentDashboard.test.js
  src/StudentDashboard/StudentForm.scss
  src/actions/index.test.js
  src/mockData/mockData.js
  src/reducers/setLessons.test.js
  src/reducers/setStudents.test.js
  src/thunks/__tests__/getLessons.js
Labels: FE, Phase 4

#80 Feature/testingandproptypes student
  src/App/App.js
  src/StudentDashboard/AnswerButton.js
  src/StudentDashboard/AnswerButton.test.js
  src/StudentDashboard/MoodForm.js
  src/StudentDashboard/MoodForm.scss
  src/StudentDashboard/MoodForm.test.js
  src/StudentDashboard/QuestionArea.js
  src/StudentDashboard/QuestionArea.scss
  src/StudentDashboard/StudentDashboard.js
  src/StudentDashboard/StudentDashboard.scss
  src/StudentDashboard/StudentDashboard.test.js
  src/StudentDashboard/StudentForm.js
  src/StudentDashboard/StudentForm.scss
  src/StudentDashboard/StudentForm.test.js
  src/index.scss
  src/reducers/setStudent.js
  src/reducers/setStudentId.js
  src/reducers/setStudentId.test.js
  src/thunks/__tests__/getStudents.js
  src/thunks/getStudents.js
Labels: FE

#81 Adds dash at end of post url to fix cors error
  src/StudentDashboard/MoodForm.js
  src/StudentDashboard/MoodForm.scss
  src/StudentDashboard/QuestionArea.scss
  src/StudentDashboard/StudentDashboard.scss
Labels: FE

#87 Feature/teacherdashboardstyling
  src/App/App.scss
  src/TeacherDashboard/TeacherDashboard.js
  src/TeacherDashboard/TeacherDashboard.scss
  src/TeacherDashboard/TeacherDashboard.test.js
  src/TeacherHeader/TeacherHeader.js
  src/TeacherHeader/TeacherHeader.scss
  src/TeacherHeader/TeacherHeader.test.js
Labels: FE, enhancement

#88 Feature/createlesson styling
  src/CreateLesson/CreateLesson.js
  src/CreateLesson/CreateLesson.test.js
  src/LessonPreview/LessonPreview.js
  src/LessonPreview/LessonPreview.scss
  src/LessonPreview/QuestionCard/QuestionCard.scss
  src/QuestionFormCard/QuestionFormCard.js
  src/QuestionFormCard/QuestionFormCard.scss
  src/QuestionFormCard/QuestionFormCard.test.js
  src/TeacherHeader/TeacherHeader.scss
Labels: FE, enhancement

#92 get lesson averagetest
  src/LessonDetails/LessonDetails.js
  src/QuestionFormCard/QuestionFormCard.scss
  src/StudentDetails/StudentDetails.js
  src/thunks/__tests__/getLessonAverage.js
  src/thunks/getLessonAverage.js
Labels: FE

#98 Fixes bugs
  src/StudentDashboard/QuestionArea.scss
  src/StudentDashboard/StudentDashboard.js
  src/TeacherDashboard/TeacherDashboard.js
  src/TeacherLessons/LessonCard/LessonCard.js
  src/TeacherLessons/LessonCard/LessonCard.scss
  src/TeacherLessons/TeacherLessons.scss
Labels: FE
